### ISSUE TITLE
AutoLayout changes

### ISSUE THREAD

**Issue by AdamBCo** [poetmountain/PMTween#3]
How would you recommend updating constraint changes with PMTween?

**Comment by poetmountain** [comment]
Well, unless you want to temporarily disable the constraints while you tween normally, I'd recommend  tweening the `constant` property of the constraints you want to modify (you'll probably want to assign the constraints to properties). I've used that method before and it works well. If you need to alter the constraints based on other properties, you can modify the `constant` property within the tween's updateBlock, such as:

```
self.tween.updateBlock = ^void(NSObject<PMTweening> *tween) {
        __strong typeof(self) strong_self = weak_self;

        strong_self.viewConstraint.constant = _________;
        [strong_self.view updateConstraintsIfNeeded];

    };
```

**Comment by AdamBCo** [comment]
@poetmountain Thanks for the help.

At the moment, I'm animating 2 views at the same time, so I was wondering what the full creation of the tween would look like. For example this is the code I have at the moment:

```
self.tabBarHeightConstraint.constant = 0;
self.tabBarSubViewConstraint.constant = 44;
[UIView animateWithDuration:animationDuration delay:animationDelay options:animationOptions animations:^{
  [self.view layoutIfNeeded];
} completion:nil];
```

What would the creation of the tween look like if I wanted to animate the constraints from the values below to the FINAL Values with a duration of 20 seconds?

```
self.tabBarHeightConstraint.constant = 44;
self.tabBarSubViewConstraint.constant = 0;
```

Final Values 

```
self.tabBarHeightConstraint.constant = 0;
self.tabBarSubViewConstraint.constant = 44;
```

I tried the following, but I get a pop animation instead:

```
self.tween = [[PMTweenUnit alloc] init];
self.tween.duration = 20;
self.tween.easingBlock = [PMTweenEasingCubic easingIn];
self.tween.repeating = NO;

self.tabBarHeightConstraint.constant = 0;
self.tabBarSubViewConstraint.constant = 44;

__weak TabBarContainerViewController *weakSelf = self;
self.tween.updateBlock = ^void(NSObject<PMTweening> *tween) {
  [weakSelf.view layoutIfNeeded];
};
[self.tween startTween];
```

Thanks for the help, I really appreciate it!

**Comment by poetmountain** [comment]
I'm not sure what exactly you're trying to do in your sample code, but you've instantiated a PMTweenUnit instance without using the initWithObject method, so it has no property to tween.
I just made a quick sample project and this works fine:

```
self.constraint = [NSLayoutConstraint constraintWithItem:self.tweenView
                                                      attribute:NSLayoutAttributeCenterY
                                                      relatedBy:NSLayoutRelationEqual
                                                         toItem:self.view
                                                      attribute:NSLayoutAttributeCenterY
                                                     multiplier:1.0
                                                       constant:0.0];
self.constraint.active = YES;

self.tween = [[PMTweenUnit alloc] initWithObject:self.constraint
                                 propertyKeyPath:@"constant"
                                   startingValue:0.0
                                     endingValue:44.0
                                        duration:1.0
                                         options:PMTweenOptionNone
                                     easingBlock:easing];
```

For each constraint, you'd need to create a separate tween. The only way to really handle multiple constraints with one tween would be to tween some dummy object, but update the constraints in the updateBlock, such as:

```
    self.tween.updateBlock = ^void(NSObject<PMTweening> *tween) {
        __strong typeof(self) strong_self = weak_self;
        PMTweenUnit *unit = (PMTweenUnit *)tween;
        strong_self.constraint.constant = (44.0 * unit.tweenProgress); // tweenProgress is 0.0 to 1.0 
        strong_self.constraint2.constant = 44.0 - (44.0 * unit.tweenProgress);
    };
```

**Comment by AdamBCo** [comment]
@poetmountain Thanks for the help on this issue. I was able to get everything working, so I really appreciate the help. I think I was getting confused on the need for a dummy object, which is why I never created a tween with an object in my example code. Thanks for developing a kick ass tweening library!

**Comment by poetmountain** [comment]
@AdamBCo Glad you got it working, and thanks for the kind words!

p.s. for reference, the quickest way of using the dummy object technique is to tween a NSNumber using the initWithProperty method, which tweens a NSValue object directly:
`self.tween = [[PMTweenUnit alloc] initWithProperty:@0 startingValue:0.0 endingValue:1.0 duration:1.0 options:PMTweenOptionNone easingBlock:easing];`
